---                                                                                                    
kind: PersistentVolume                                                          
apiVersion: v1                                                                  
metadata:                                                                      
 name: jenkins-pv                                                              
spec:                                                                          
 storageClassName: jenkins-pv                                                  
 capacity:                                                                    
   storage: 8Gi                                                                
 accessModes:                                                                  
   - ReadWriteOnce                                                            
 persistentVolumeReclaimPolicy: Retain                                        
 hostPath:                                                                    
   path: "/mnt/k8s_volume/jenkins_home"
